apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgp-static-ip-node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bgp-static-ip-node-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bgp-static-ip-node-reader
subjects:
- kind: ServiceAccount
  name: bgp-static-ip
  namespace: bgp-static-ip
